### ISSUE TITLE
Runtime Error - ArgumentNullException

### ISSUE THREAD

**Issue by buraksenyurt** [buraksenyurt/DistributedChallenge#12]
Hi @ismkdc ,

After entering a report request from the WebApp, the EventHost application throws the following runtime error while processing the event.  We need to take a look at this.

```text
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'returnType')
   at System.Text.Json.ThrowHelper.ThrowArgumentNullException(String parameterName)
   at System.Text.Json.JsonSerializer.Deserialize(ReadOnlySpan`1 utf8Json, Type returnType, JsonSerializerOptions options)
   at GamersWorld.EventHost.EventConsumer.Handle(String eventType, Byte[] eventMessage) in /home/buraks/development/DistributedChallenge/GamersWorld.EventHost/EventConsumer.cs:line 65
   at GamersWorld.EventHost.EventConsumer.<Run>b__4_0(Object model, BasicDeliverEventArgs args) in /home/buraks/development/DistributedChallenge/GamersWorld.EventHost/EventConsumer.cs:line 44
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

**Comment by ismkdc** [comment]
this pr should be fix it.
https://github.com/buraksenyurt/DistributedChallenge/pull/13/commits
